### ISSUE TITLE
infinite loop when pressing backspace in an EditBox 

### ISSUE THREAD

**Issue by silentwings** [jk3064/chiliui#45] opened 2016-02-08 23:52 UTC
see https://springrts.com/mantis/view.php?id=5072 for details, maybe has already been fixed

**Comment by gajop** [comment] 2016-02-09 00:09
Was about to write a response on mantis but beaten to it by you guys :)
Anyway, this isn't an engine issue and neither is it a chili one.
The problem is in your widget, you shouldn't set text in the editbox by modifying the .text property, but instead invoke the :SetText() method.
Change line 793 in bgu_mainMenu.lua widget:
```
addScrollStack{name='widgetList',x='50%'},           Chili.EditBox:New{name='widgetFilter',x=0,y=0,width = '35%',text=' Enter filter -> Hit Return,  or -->',OnMouseDown = {function(obj) obj:SetText('') end}},
```

PS: You may also want to update your chili eventually

**Comment by gajop** [comment] 2016-02-09 00:11
In addition, the new chili/editbox supports the "hint" field which you could use, so instead of
```
text=' Enter filter -> Hit Return,  or -->'
```
```
hint=' Enter filter -> Hit Return,  or -->'
```

**Comment by silentwings** [comment] 2016-02-09 00:31
I didn't write this code - but how is anyone supposed to tell which fields are safe to set as arguments to the constructor and which are only safe to set via wrapper functions? As far as I can see http://gajop.github.io/chiliui/modules/controls.editbox.htmlmakes no such distinction.

**Comment by gajop** [comment] 2016-02-09 00:34
All fields are safe to be set via constructors, but this isn't the issue here.
The original code set the field in the OnMouseUp chili callback:
```lua
OnMouseDown = {function(obj) obj.text  = '' end}
```

Regarding wrapper methods, they should always be used if they exist (e.g. if there's a SetX method, then you should call that instead of setting the .x property directly).

**Comment by silentwings** [comment] 2016-02-09 00:36
Oh, you are correct, I didn't scroll far enough right... thanks.

**Comment by gajop** [comment] 2016-02-09 01:08
So, can you close this issue? :p

**Comment by silentwings** [comment] 2016-02-09 10:55
No, because I don't have any priviledges for this repository.

**Closed** 2016-02-12 14:04 UTC
